name: MSIXAppPackageUpdate
on:   
      workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: microsoft/microsoft-store-apppublisher@v1.1
    - run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --sellerId ${{ secrets.SELLER_ID }} --clientId ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
    - name: Publish App package
      run: msstore publish '${{ github.workspace }}/Apps/MSTestApp201/MSTestApp201.msixbundle' -id "9NDRMZKRHKG3"
